CREATE TABLE Ingredients (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	IngredientName NVARCHAR(50) NOT NULL,
	IngredientCategory NVARCHAR(15) NOT NULL,
	Calories FLOAT NOT NULL,
	Fats FLOAT NOT NULL,
	Carbs FLOAT NOT NULL,
	Proteins FLOAT NOT NULL,
	ApprovedStatus BIT NOT NULL,
);

CREATE TABLE Recipes (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	RecipeName NVARCHAR(50) NOT NULL,
	Author NVARCHAR(20) NOT NULL,
	RecipeDescription NVARCHAR(200) NOT NULL,
	MealType NVARCHAR(15) NOT NULL,
	ServingTime NVARCHAR(15) NOT NULL,
	Servings FLOAT NOT NULL,
	Calories FLOAT NOT NULL,
	Fats FLOAT NOT NULL,
	Carbs FLOAT NOT NULL,
	Proteins FLOAT NOT NULL,
	ApprovedStatus BIT NOT NULL,
);

CREATE TABLE MealPlans (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Calories FLOAT NOT NULL,
	Fats FLOAT NOT NULL,
	Carbs FLOAT NOT NULL,
	Proteins FLOAT NOT NULL,
);

CREATE TABLE RecipeIngredients (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	RecipeId INT NOT NULL FOREIGN KEY REFERENCES Recipes(ID),
	IngredientId INT NOT NULL FOREIGN KEY REFERENCES Ingredients(ID)
);

CREATE TABLE MealPlanRecipes (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MealPlanId INT NOT NULL FOREIGN KEY REFERENCES MealPlans(ID),
	RecipeId INT NOT NULL FOREIGN KEY REFERENCES Recipes(ID)
);